### PR TITLE
Small corrections and precisions in french translation

### PR DESCRIPTION
**Pull request by Spheerys**

### CODE REVIEW

**Comment by Spheerys** [comment]
few precisions

**Comment by electrickite** [comment]
Thanks @Spheerys

Would you mind rebasing this PR into a single commit? It'll help keep the repo history clean.

http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

**Comment by Spheerys** [comment]
Uhhhhhhh.
I'm not a git expert and I need help.
They are saying :

```
$ git fetch upstream
$ git checkout omgpull 
$ git rebase -i upstream/master

< choose squash for all of your commits, except the first one >
< Edit the commit message to make sense, and describe all your changes >

$ git push origin omgpull -f
```

In my case, what is omgpull and upstream ?

**Comment by electrickite** [comment]
In their example `upstream` is the name of the remote for my repository. In your case, it looks like it's called `electrickite`. `omgpull` should be the name of the branch with your changes, which seems to be `master`.

So, the whole command should probably be:

```
$ git fetch electrickite
$ git checkout master
$ git rebase -i electrickite/master

< choose squash for all of your commits, except the first one >
< Edit the commit message to make sense, and describe all your changes >

$ git push origin master -f
```

**Comment by Spheerys** [comment]
Hummm it's unfortunatly not so simple, probably because I'm doing it wrong.
To make change on your code, I did this :
1. I do a fork of your project in my account
2. I made a git clone git@github.com:Spheerys/geotv.git
3. I made change locally on my computer
4. push on my repository (Spheerys/geotv.git)
5. make a pull request from my repository to yours with the GitHub interface

Two times, this process works.

But know you asking me something weird :D
And if locally, on my computer, I try do do a "git fetch electrickite", I obviously have this error :

```
fatal: 'electrickite' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

What's wrong on my workflow ?

**Comment by electrickite** [comment]
Can you run `git remote -v` and post the output?

**Comment by Spheerys** [comment]
```
origin  git@github.com:Spheerys/geotv.git (fetch)
origin  git@github.com:Spheerys/geotv.git (push)
```

**Comment by electrickite** [comment]
Ok. I doesn't look like you have a remote set up for my repo. You can add one like this:

```
$ git remote add electrickite https://github.com/electrickite/geotv.git
```

And then run the commands above.

**Comment by Spheerys** [comment]
ok I did it : 

```
$ git push origin master -f                                                                                             
Décompte des objets: 9, fait.
Delta compression using up to 4 threads.
Compression des objets: 100% (6/6), fait.
Écriture des objets: 100% (9/9), 812 bytes | 0 bytes/s, fait.
Total 9 (delta 3), reused 0 (delta 0)
To git@github.com:Spheerys/geotv.git
 + 4171e86...d90133f master -> master (forced update)

```

**Comment by electrickite** [comment]
Wonderful! Thanks for taking the time to do that. Helps keep the commit history clean. I'm going to get a contributing file uploaded soon so these kinds of things are documented.

**Comment by Spheerys** [comment]
Thanks to you to take taime to explain me :)

**Pull request merged**
